app:
  services:
    prometheus:
      enabled: true
    loki:
      enabled: true
    tempo:
      enabled: true
    grafana:
      enabled: true
    argocd:
      base-url: ${ARGOCD_URL:http://localhost:30080}
      auth-token: ${ARGOCD_AUTH_TOKEN}
      enabled: true
    pagerduty:
      base-url: ${PAGERDUTY_URL:https://api.pagerduty.com}
      api-key: ${PAGERDUTY_API_KEY}
      enabled: true
    slack:
      webhook-url: ${SLACK_WEBHOOK_URL}
      enabled: true
